export type Activity = { name: string; xp: number; freq: 'Daily' | 'Weekly' | 'Monthly' | 'Annual' };
export type Category = { title: string; activities: Activity[] };

export function getTitle(level: number): string {
  if (level < 10) return 'New Beginning';
  if (level < 30) return 'Gaining Momentum';
  if (level < 50) return 'Locked In';
  if (level < 70) return 'Building a New Life';
  if (level < 90) return 'Leveled Up';
  return 'The One Who Never Quit';
}

export function getXpForLevel(level: number): number {
  let baseLevelXp = 500;
  let growthRate = 0.10;
  for (let levelNum = 2; levelNum < level; levelNum++) {
    baseLevelXp = baseLevelXp * (1 + growthRate);
    growthRate -= 0.0015;
    growthRate = Math.max(growthRate, 0.005);
  }
  return Math.round(baseLevelXp / 5) * 5;
}

export const ALL = ['Healthy Guy', 'Gymbro / Athlete', 'Entrepreneur', 'Scholar', 'Creator', 'Monk', 'Social Guy', 'Family Man', 'Looksmaxer', 'Jack of All Trades'];

export const categories: Category[] = [
  {
    title: 'Morning',
    activities: [
      { name: 'Wake up when said without fuss', xp: 25, freq: 'Daily' },
      { name: 'No phone for 60 min after waking', xp: 75, freq: 'Daily' },
      { name: 'Delay coffee 90 min after waking', xp: 25, freq: 'Daily' },
      { name: 'Morning routine', xp: 75, freq: 'Daily' },
      { name: 'Nutrient dense breakfast', xp: 25, freq: 'Daily' },
    ],
  },
  {
    title: 'Nutrition',
    activities: [
      { name: 'At least 3L of water', xp: 25, freq: 'Daily' },
      { name: 'Hit daily protein and calories', xp: 75, freq: 'Daily' },
      { name: 'Eating healthy (no sugar, no processed, RDIs)', xp: 200, freq: 'Daily' },
      { name: 'Taking supplements', xp: 25, freq: 'Daily' },
      { name: 'Debloat protocol', xp: 75, freq: 'Daily' },
    ],
  },
  {
    title: 'Physical',
    activities: [
      { name: 'Any form of cardio', xp: 150, freq: 'Daily' },
      { name: 'Training (weights/calisthenics/plyometrics)', xp: 150, freq: 'Daily' },
      { name: 'Gym rest day', xp: 75, freq: 'Daily' },
      { name: 'Stretching', xp: 75, freq: 'Daily' },
      { name: 'Cold shower', xp: 75, freq: 'Daily' },
      { name: 'Sauna', xp: 75, freq: 'Daily' },
      { name: 'Going for a walk', xp: 25, freq: 'Daily' },
      { name: 'Digestive walk', xp: 25, freq: 'Daily' },
      { name: 'Good posture', xp: 200, freq: 'Daily' },
      { name: 'Sleep (7-9 hours)', xp: 75, freq: 'Daily' },
    ],
  },
  {
    title: 'Appearance',
    activities: [
      { name: 'Skincare routine', xp: 25, freq: 'Daily' },
      { name: 'Mewing', xp: 200, freq: 'Daily' },
      { name: 'Mouth taping', xp: 25, freq: 'Daily' },
      { name: 'At least 30 min sunlight (with SPF)', xp: 25, freq: 'Daily' },
    ],
  },
  {
    title: 'Mind & Learning',
    activities: [
      { name: 'Working in deep focus (1hr minimum)', xp: 150, freq: 'Daily' },
      { name: 'Learning (general)', xp: 75, freq: 'Daily' },
      { name: 'Learn something directly applicable to business', xp: 150, freq: 'Daily' },
      { name: 'Study session', xp: 150, freq: 'Daily' },
      { name: 'Learn a new skill (15 min minimum)', xp: 75, freq: 'Daily' },
      { name: 'Reading (15 min or 10 pages minimum)', xp: 75, freq: 'Daily' },
      { name: 'Listening to a podcast (30 min minimum)', xp: 75, freq: 'Daily' },
      { name: 'Active recall / flashcard session', xp: 75, freq: 'Daily' },
      { name: 'Teach someone what you learned today', xp: 75, freq: 'Daily' },
      { name: 'Write a summary of what you studied', xp: 75, freq: 'Daily' },
      { name: 'Language practice session', xp: 75, freq: 'Daily' },
      { name: 'Solve a problem from scratch', xp: 150, freq: 'Daily' },
    ],
  },
  {
    title: 'Habits & Discipline',
    activities: [
      { name: 'No lustful behaviours', xp: 200, freq: 'Daily' },
      { name: 'No unnecessary social media', xp: 200, freq: 'Daily' },
      { name: 'Not on phone too much', xp: 200, freq: 'Daily' },
      { name: 'Doing something you hate daily', xp: 150, freq: 'Daily' },
      { name: 'View sunset', xp: 25, freq: 'Daily' },
    ],
  },
  {
    title: 'Mind & Reflection',
    activities: [
      { name: 'Meditating/NSDR/breathing exercises', xp: 75, freq: 'Daily' },
      { name: 'Sit in silence 10 min', xp: 25, freq: 'Daily' },
      { name: 'Journal', xp: 75, freq: 'Daily' },
      { name: 'Doing something creative', xp: 75, freq: 'Daily' },
      { name: 'Think before speaking (end of day reflection)', xp: 200, freq: 'Daily' },
      { name: 'Standing for your morals (end of day reflection)', xp: 200, freq: 'Daily' },
      { name: 'Being grounded (end of day reflection)', xp: 200, freq: 'Daily' },
      { name: 'Be content with yourself (end of day reflection)', xp: 200, freq: 'Daily' },
    ],
  },
  {
    title: 'Social',
    activities: [
      { name: 'Being social', xp: 75, freq: 'Daily' },
      { name: 'Initiate a conversation with a stranger', xp: 150, freq: 'Daily' },
      { name: 'Give someone a genuine compliment', xp: 25, freq: 'Daily' },
      { name: 'Organise or attend a social event', xp: 150, freq: 'Daily' },
      { name: "Call or meet a friend you haven't spoken to in a while", xp: 75, freq: 'Daily' },
      { name: 'Practice public speaking (mirror/recording)', xp: 150, freq: 'Daily' },
      { name: 'Active listening — full presence, no phone', xp: 75, freq: 'Daily' },
      { name: 'Do something kind without expecting anything', xp: 75, freq: 'Daily' },
      { name: 'Networking', xp: 150, freq: 'Daily' },
    ],
  },
  {
    title: 'Family',
    activities: [
      { name: 'Spend quality time with family (no phones)', xp: 150, freq: 'Daily' },
      { name: 'Have a meaningful conversation with a family member', xp: 75, freq: 'Daily' },
      { name: 'Plan a family activity', xp: 75, freq: 'Daily' },
      { name: 'Financial planning session', xp: 150, freq: 'Daily' },
      { name: 'Tell someone you love them', xp: 25, freq: 'Daily' },
    ],
  },
  {
    title: 'Creator',
    activities: [
      { name: 'Publish something (post, video, article)', xp: 150, freq: 'Daily' },
      { name: 'Brainstorm session (15 min minimum)', xp: 75, freq: 'Daily' },
      { name: "Study someone you admire's work", xp: 75, freq: 'Daily' },
      { name: 'Engage with your audience', xp: 75, freq: 'Daily' },
      { name: 'Batch content creation session (1hr minimum)', xp: 150, freq: 'Daily' },
      { name: 'Seek feedback on your work', xp: 75, freq: 'Daily' },
    ],
  },
  {
    title: 'Entrepreneur',
    activities: [
      { name: 'Review finances/business metrics', xp: 75, freq: 'Daily' },
      { name: 'Outreach to a potential client or collaborator', xp: 150, freq: 'Daily' },
      { name: 'Work on the business not in it (30min strategic)', xp: 150, freq: 'Daily' },
      { name: 'Sales or negotiation practice', xp: 150, freq: 'Daily' },
    ],
  },
  {
    title: 'Weekly',
    activities: [
      { name: '1 hour silence', xp: 150, freq: 'Weekly' },
    ],
  },
  {
    title: 'Monthly',
    activities: [
      { name: '1 day fast', xp: 750, freq: 'Monthly' },
      { name: 'Skill audit', xp: 750, freq: 'Monthly' },
    ],
  },
  {
    title: 'Annual',
    activities: [
      { name: 'Misogi', xp: 150, freq: 'Annual' },
      { name: "New Year's review", xp: 500, freq: 'Annual' },
      { name: '1 week total digital detox', xp: 1000, freq: 'Annual' },
    ],
  },
];

export const activityExplanations: Record<string, string> = {
  'Wake up when said without fuss': 'If you set an alarm for 6:00 the latest you will be out of bed and starting your day is 6:05.',
  'No phone for 60 min after waking': 'Your brain is in its most impressionable state right after waking. Feed it noise and you set a scattered tone for the whole day.',
  'Delay coffee 90 min after waking': 'Cortisol peaks naturally in the first 90 minutes. Delaying coffee lets that peak do its job — adding caffeine on top just builds tolerance and crashes you harder.',
  'Morning routine': 'No phone for 60 minutes, morning sunlight, moving your body, drinking water, coffee with a 90 minute delay, taking care of your body.',
  'Nutrient dense breakfast': 'The first meal you eat sets the tone for your energy, focus and discipline for the rest of the day. Load it with protein, vitamins and minerals and your body will thank you by midday.',
  'At least 3L of water': 'Water is the single most important substance for your body. Make sure you consume enough of it.',
  'Hit daily protein and calories': 'Without this your body will never reach its peak, therefore your mind will never reach its peak.',
  'Eating healthy (no sugar, no processed, RDIs)': 'What you consume shows up in your energy, motivation and discipline. Make sure you consume the right things.',
  'Taking supplements': "To truly max out your body's potential you need to take some supplements.",
  'Debloat protocol': 'Makes you feel better, look better, less bloated. More alive.',
  'Any form of cardio': 'With sweat and pain going out, self-respect and a healthier body come in.',
  'Gym rest day': 'A rest day is worth more than a day spent training. That said you cannot have results without both.',
  'Training (weights/calisthenics/plyometrics)': 'Believe it or not, training hard not only betters your body but also your mind.',
  'Stretching': 'Stiffness can limit your output and make you more injury prone.',
  'Cold shower': 'Along with recovery it builds extreme discipline and self-respect.',
  'Sauna': 'Studies have shown a 50% decrease in cardiovascular disease, a testosterone and growth hormone increase in people who regularly use saunas.',
  'Going for a walk': 'Clears the mind. Moves the body. Decreases cortisol. What more could you ask for?',
  'Digestive walk': 'A short walk after a meal improves digestion, reduces bloating and blood sugar spikes.',
  'Good posture': 'Poor posture compresses your spine, reduces lung capacity and signals low confidence to everyone around you. Fix it and your energy, breathing and presence all improve immediately.',
  'Sleep (7-9 hours)': 'Without it nothing else matters.',
  'Skincare routine': 'Taking care of the organ that protects your whole body is a must.',
  'Mewing': 'A few consistent months of mewing can change the way your whole face looks.',
  'Mouth taping': 'Taping your mouth during sleep forces nasal breathing overnight, which filters air, regulates your nervous system and leads to deeper, more restorative sleep.',
  'At least 30 min sunlight (with SPF)': 'Staying in the sun is one of the highest ROI habits, up there with sleep, diet and exercise.',
  'Working in deep focus (1hr minimum)': 'The key word here is deep focus, you should have absolutely no distractions. Working time is for working.',
  'Learning (general)': 'The more you know the better your decisions. The better your decisions the better your life. 15 minutes a day compounds into something most people will never have.',
  'Learn something directly applicable to business': 'Your main investment is you after all, not the business.',
  'Study session': 'Learning is the key to understanding everything. Make sure you pay attention though.',
  'Learn a new skill (15 min minimum)': 'If you have some downtime it is better to spend time learning something new instead of filling your brain with dopamine junk.',
  'Reading (15 min or 10 pages minimum)': 'Reading is the most underrated skill even though it is so hyped.',
  'Listening to a podcast (30 min minimum)': 'The opportunity is sitting here to get so much insight and wisdom. You just have to open the door.',
  'Active recall / flashcard session': 'One of the best ways of learning since the more you use it the more you remember it.',
  'Teach someone what you learned today': 'If you cannot teach it to someone you do not understand it yet.',
  'Write a summary of what you studied': 'While writing the brain stores especially well.',
  'Language practice session': 'Languages are the keys to connections and therefore opportunities.',
  'Solve a problem from scratch': 'Forcing your brain to be adaptable will come in handy when it has no other choice but to adapt.',
  'No lustful behaviours': 'Engaging in lustful behaviours crashes baseline dopamine levels making you unmotivated and lazy.',
  'No unnecessary social media': 'Social media is engineered to hijack your brain from important tasks. A little bit is fine and can be beneficial, just make sure not to overdo it.',
  'Not on phone too much': 'You said just one more game, video, Instagram story five times today already. When is it going to end?',
  'Doing something you hate daily': 'This can actually be trained making other stuff like work, training and other hard things easier to do.',
  'View sunset': 'Reduces stress, increases mood, improves sleep quality and starts your wind-down routine for the night.',
  'Meditating/NSDR/breathing exercises': 'Meditation improves focus, reduces stress and helps with your mental well-being.',
  'Sit in silence 10 min': 'A quick dopamine reset increasing focus.',
  'Journal': 'Setting goals for the day or reviewing the day can both be key to achieving more.',
  'Doing something creative': 'With AI coming and individuality being oppressed creativity might just be the skill to make or break a person.',
  'Think before speaking (end of day reflection)': 'A simple action that helps the quality of your conversations so much.',
  'Standing for your morals (end of day reflection)': 'Standing alone might be hard but is it harder than lying to yourself?',
  'Being grounded (end of day reflection)': "In today's society where everyone cares more about their image rather than their character being grounded makes you stand out.",
  'Be content with yourself (end of day reflection)': 'One of the hardest things to do is liking yourself, but if you manage to do it your life quality will be through the roof.',
  'Being social': 'Talk to random people, give a compliment here and there, be open to approach, talk to your friends, enjoy being around people.',
  'Initiate a conversation with a stranger': 'You never know who you might just meet.',
  'Give someone a genuine compliment': 'You do not know if someone is having a hard day and you might have just made it.',
  'Organise or attend a social event': 'Some of the best experiences come from a random Tuesday night made on a whim.',
  "Call or meet a friend you haven't spoken to in a while": 'Might just be the best decision you make to reconnect with a lost friend.',
  'Practice public speaking (mirror/recording)': 'What you do in quiet shows up in public.',
  'Active listening — full presence, no phone': 'One of the most valuable things you have is your attention and you choose to give it to someone.',
  'Do something kind without expecting anything': 'It not only helps the person you did something for but also you. It is a win-win.',
  'Networking': 'Your net worth is the quality of your connections.',
  'Spend quality time with family (no phones)': 'Quality time with the best people is always worth it.',
  'Have a meaningful conversation with a family member': 'Gives natural dopamine not to mention connecting with your loved ones.',
  'Plan a family activity': 'Spending time with the people you love most in the world is the best thing.',
  'Financial planning session': 'It can really improve the quality of life if your finances are in check.',
  'Tell someone you love them': 'You do not know how much time you or they have left so say it with all your heart.',
  'Publish something (post, video, article)': 'Posting consistently is the number one thing determining whether you go viral or not.',
  'Brainstorm session (15 min minimum)': 'The best ideas sometimes come in the most ordinary moments.',
  "Study someone you admire's work": 'Having a mentor can be a crucial piece deciding if you make it or not.',
  'Engage with your audience': 'How would you feel if your favourite creator responded to you? Probably good. So be that person.',
  'Batch content creation session (1hr minimum)': 'It is a good thing being prepared in cases of emergencies.',
  'Seek feedback on your work': 'The best way to improve is to take constructive criticism from multiple sources.',
  'Review finances/business metrics': 'Make sure you know where everything is going and coming from.',
  'Outreach to a potential client or collaborator': 'Takes 5-10 minutes and can make a ton of money.',
  'Work on the business not in it (30min strategic)': 'Working 16 hour days while someone with 4 hour days is getting the same output is not being locked in.',
  'Sales or negotiation practice': 'Makes you sharper and more confident when the actual time comes.',
  '1 hour silence': 'The best dopamine reset. Allowing your brain to wander and go to new places can bring out the most amazing ideas.',
  '1 day fast': 'A hard reset can do wonders for your metabolism. Make sure you consult a professional if any problems come up.',
  'Skill audit': 'Learning a new skill once a month compounds really fast, before you know it you\'ll become a polyhistor.',
  'Misogi': 'Doing a task with a 50% failure rate is a tough challenge, but if you manage to do it you will feel like you can do anything.',
  "New Year's review": 'This one is a must for everyone trying to better themselves.',
  '1 week total digital detox': 'Resets dopamine, makes you feel alive again and is also a test of your discipline.',
};

export const activityArchetypes: Record<string, string[]> = {
  'Wake up when said without fuss': ALL,
  'No phone for 60 min after waking': ['Monk', 'Entrepreneur', 'Scholar', 'Healthy Guy'],
  'Delay coffee 90 min after waking': ['Healthy Guy', 'Monk', 'Entrepreneur'],
  'Morning routine': ALL,
  'Nutrient dense breakfast': ['Healthy Guy', 'Gymbro / Athlete', 'Looksmaxer'],
  'At least 3L of water': ['Healthy Guy', 'Gymbro / Athlete', 'Looksmaxer'],
  'Hit daily protein and calories': ['Gymbro / Athlete', 'Healthy Guy'],
  'Eating healthy (no sugar, no processed, RDIs)': ['Healthy Guy', 'Gymbro / Athlete', 'Family Man', 'Looksmaxer'],
  'Taking supplements': ['Gymbro / Athlete', 'Healthy Guy', 'Looksmaxer'],
  'Debloat protocol': ['Healthy Guy', 'Looksmaxer'],
  'Any form of cardio': ['Gymbro / Athlete', 'Healthy Guy', 'Family Man', 'Looksmaxer'],
  'Training (weights/calisthenics/plyometrics)': ['Gymbro / Athlete', 'Healthy Guy'],
  'Gym rest day': ['Gymbro / Athlete', 'Healthy Guy', 'Looksmaxer'],
  'Stretching': ['Gymbro / Athlete', 'Healthy Guy', 'Monk'],
  'Cold shower': ['Monk', 'Gymbro / Athlete', 'Healthy Guy'],
  'Sauna': ['Gymbro / Athlete', 'Healthy Guy', 'Monk'],
  'Going for a walk': ['Healthy Guy', 'Monk', 'Family Man', 'Looksmaxer', 'Gymbro / Athlete'],
  'Digestive walk': ['Healthy Guy', 'Looksmaxer'],
  'Good posture': ['Looksmaxer', 'Gymbro / Athlete', 'Healthy Guy'],
  'Sleep (7-9 hours)': ALL,
  'Skincare routine': ['Looksmaxer', 'Healthy Guy'],
  'Mewing': ['Looksmaxer'],
  'Mouth taping': ['Looksmaxer', 'Healthy Guy', 'Monk'],
  'At least 30 min sunlight (with SPF)': ['Healthy Guy', 'Looksmaxer'],
  'Working in deep focus (1hr minimum)': ['Entrepreneur', 'Scholar', 'Creator'],
  'Learning (general)': ['Jack of All Trades', 'Healthy Guy', 'Gymbro / Athlete', 'Monk', 'Family Man', 'Looksmaxer'],
  'Learn something directly applicable to business': ['Entrepreneur'],
  'Study session': ['Scholar'],
  'Learn a new skill (15 min minimum)': ['Jack of All Trades', 'Entrepreneur', 'Creator', 'Monk', 'Social Guy'],
  'Reading (15 min or 10 pages minimum)': ['Scholar', 'Monk', 'Entrepreneur'],
  'Listening to a podcast (30 min minimum)': ['Scholar', 'Entrepreneur', 'Creator'],
  'Active recall / flashcard session': ['Scholar'],
  'Teach someone what you learned today': ['Scholar'],
  'Write a summary of what you studied': ['Scholar'],
  'Language practice session': ['Scholar'],
  'Solve a problem from scratch': ['Scholar'],
  'No lustful behaviours': ALL,
  'No unnecessary social media': ['Healthy Guy', 'Scholar'],
  'Not on phone too much': ['Healthy Guy', 'Scholar'],
  'Doing something you hate daily': ['Entrepreneur', 'Gymbro / Athlete', 'Monk', 'Scholar'],
  'View sunset': ['Monk', 'Creator', 'Healthy Guy'],
  'Meditating/NSDR/breathing exercises': ['Monk', 'Healthy Guy', 'Entrepreneur'],
  'Sit in silence 10 min': ['Monk', 'Scholar', 'Entrepreneur'],
  'Journal': ['Monk', 'Scholar', 'Creator', 'Entrepreneur'],
  'Doing something creative': ['Creator', 'Jack of All Trades'],
  'Think before speaking (end of day reflection)': ['Monk', 'Social Guy', 'Family Man'],
  'Standing for your morals (end of day reflection)': ['Monk', 'Family Man', 'Social Guy'],
  'Being grounded (end of day reflection)': ['Monk', 'Family Man'],
  'Be content with yourself (end of day reflection)': ['Monk', 'Healthy Guy'],
  'Being social': ['Social Guy', 'Family Man'],
  'Initiate a conversation with a stranger': ['Social Guy'],
  'Give someone a genuine compliment': ['Social Guy', 'Family Man'],
  'Organise or attend a social event': ['Social Guy', 'Family Man'],
  "Call or meet a friend you haven't spoken to in a while": ['Social Guy', 'Family Man'],
  'Practice public speaking (mirror/recording)': ['Social Guy', 'Entrepreneur'],
  'Active listening — full presence, no phone': ['Social Guy', 'Family Man', 'Monk'],
  'Do something kind without expecting anything': ['Social Guy', 'Family Man', 'Monk'],
  'Networking': ['Entrepreneur'],
  'Spend quality time with family (no phones)': ['Family Man'],
  'Have a meaningful conversation with a family member': ['Family Man'],
  'Plan a family activity': ['Family Man'],
  'Financial planning session': ['Family Man', 'Entrepreneur'],
  'Tell someone you love them': ['Family Man'],
  'Publish something (post, video, article)': ['Creator'],
  'Brainstorm session (15 min minimum)': ['Creator', 'Entrepreneur'],
  "Study someone you admire's work": ['Creator', 'Scholar'],
  'Engage with your audience': ['Creator'],
  'Batch content creation session (1hr minimum)': ['Creator'],
  'Seek feedback on your work': ['Creator', 'Entrepreneur'],
  'Review finances/business metrics': ['Entrepreneur'],
  'Outreach to a potential client or collaborator': ['Entrepreneur'],
  'Work on the business not in it (30min strategic)': ['Entrepreneur'],
  'Sales or negotiation practice': ['Entrepreneur'],
  '1 hour silence': ['Monk', 'Entrepreneur'],
  '1 day fast': ['Monk', 'Healthy Guy'],
  'Skill audit': ['Entrepreneur', 'Scholar', 'Jack of All Trades'],
  'Misogi': ALL,
  "New Year's review": ALL,
  '1 week total digital detox': ['Monk', 'Healthy Guy', 'Entrepreneur'],
};

export const dailyQuotes: string[] = [
  // Bálint's originals (34)
  "Winners lose more than losers ever will.",
  "If you don't sacrifice for what you want, what you want becomes the sacrifice.",
  "A man crawling in confusion moves further than a man standing in doubt.",
  "Every man takes the limits of his own field of vision for the limits of the world.",
  "Pain is weakness leaving the body.",
  "It is not death one should fear, but never beginning to live.",
  "It is hard to fail, but it is harder never to have tried succeeding.",
  "Nothing changes if nothing changes.",
  "Never sacrifice what you want most for what you want in the moment.",
  "A star does not see the way it shines.",
  "The higher you soar, the smaller you seem to those who cannot fly.",
  "By pursuing the person you want to be, you are already him.",
  "What a privilege it is to be disappointed by a result once thought unreachable.",
  "Don't wish for an easier path. Wish for stronger legs.",
  "The greatest fisherman cannot show off their skills on a calm sea.",
  "The darkness only makes the stars easier to see.",
  "To become a star you must burn.",
  "If you want a rainbow you have to deal with the rain.",
  "Until you win, effort goes unnoticed.",
  "Believe you can and you are halfway there.",
  "The day you plant the seed is not the day you eat the fruit.",
  "Life shrinks or expands according to one's courage.",
  "There is nothing impossible to him who will try.",
  "What a blessing it is to be tired in a challenge of your own choosing.",
  "I know of no better purpose of life than to perish in attempting the great and impossible.",
  "Differentiation is survival when the universe wants you to be typical.",
  "A man who loves walking will walk further than a man who loves the destination.",
  "A lack of confidence kills more dreams than a lack of skill.",
  "Be the change that you wish to see in the world.",
  "He who has a why can bear almost any how.",
  "What you do in quiet shows up in public.",
  "The man who avoids the storm never learns how to steer a ship.",
  "You don't learn about swimming by reading about water.",
  "To get something you never had, you have to do something you have never done.",
  "Being better is not a future version — it is a daily choice.",
  "The smoothest stones had the roughest journeys.",

  // New (329)
  "Discipline is not a cage. It is the key.",
  "The version of you that quit is not coming back.",
  "Most people are defeated by the ordinary.",
  "You will not drift into the person you want to be.",
  "The body keeps the score. Make sure it reads well.",
  "Comfort is a slow poison dressed as a reward.",
  "Every rep you don't do is a rep the next man does.",
  "Your excuses are your autobiography.",
  "You are not tired. You are untrained.",
  "The war is won before the battle begins.",
  "Silence is the loudest answer to doubt.",
  "You cannot negotiate with entropy. Only outwork it.",
  "Average is contagious. So is greatness.",
  "The man you are becoming is watching the man you are right now.",
  "How you do one thing is how you do everything.",
  "You don't rise to the occasion. You fall to your level of preparation.",
  "Every morning is a second chance you didn't earn.",
  "The goal is not to be motivated. The goal is to not need it.",
  "Regret weighs more than exhaustion.",
  "You are either building your future or someone else's.",
  "Hard days are not interruptions. They are the curriculum.",
  "No one is coming to save you. That is the good news.",
  "The man who wakes up early is already ahead before the race starts.",
  "Hunger is not a feeling. It is a decision.",
  "Small actions repeated become an identity.",
  "If you are not growing you are rotting. There is no pause.",
  "The crowd is almost always wrong. Study who is not in it.",
  "Your habits are a vote for who you are becoming.",
  "You cannot cheat the mirror.",
  "Progress is not a straight line. It is a test of endurance.",
  "The best investment you will ever make is the one you make in yourself.",
  "You are not your past. You are your next decision.",
  "Mediocrity does not happen overnight. Neither does excellence.",
  "The mountain does not care about your feelings. Climb anyway.",
  "One more rep separates the good from the great.",
  "What you tolerate you teach.",
  "A man without direction is fuel without fire.",
  "Your potential is not a promise. It is a responsibility.",
  "The only competition worth caring about is yesterday's version of you.",
  "Weak men wait for perfect conditions. Strong men create them.",
  "The work you avoid is usually the work that matters most.",
  "You are the average of the five habits you repeat most.",
  "Greatness is rented, not owned. The payment is daily.",
  "The cost of discipline is always less than the cost of regret.",
  "Fear is not a stop sign. It is a direction.",
  "Every champion was once a beginner who refused to stay one.",
  "The weight doesn't get lighter. You get stronger.",
  "You cannot pour from an empty cup. Fill it first.",
  "Time will pass regardless. Use it or lose it.",
  "You are not behind. You are exactly where your effort put you.",
  "The seed of every great life is a single decision made in private.",
  "Do not wait for perfect. Perfect never comes. Go now.",
  "The ones who show up when it is hard are the ones who end up somewhere.",
  "You will always have reasons not to. Do it anyway.",
  "Effort is the one currency that always holds its value.",
  "The man who makes excuses and the man who makes progress never swap places.",
  "Stop negotiating with your alarm clock.",
  "Pride in your work is not arrogance. It is evidence.",
  "Every great story starts with a version of you that didn't quit.",
  "What got you here will not get you there. Evolve or stagnate.",
  "You are either in control of your day or it is in control of you.",
  "Most people would rather look successful than do what success requires.",
  "The only shortcut is through.",
  "You cannot outrun your identity. Change it first.",
  "Consistency beats intensity every single time.",
  "Champions do not have bad days. They have harder training days.",
  "You were not built for comfort. You were built to endure.",
  "The man who reads lives a thousand lives. The man who doesn't lives one.",
  "Pressure does not create diamonds. Sustained pressure does.",
  "Stop waiting to feel ready. You get ready by starting.",
  "What you do when no one is watching is who you actually are.",
  "The mind quits long before the body does.",
  "Every sacrifice you make today is compounding in your favour.",
  "You will not remember the days you rested. You will remember the days you pushed.",
  "Talent is common. Consistency is rare.",
  "Your future self is watching your present decisions.",
  "The grind is not glamorous until the results arrive.",
  "More people fail from lack of trying than lack of talent.",
  "The man who controls his morning controls his day.",
  "Standards are not set once. They are defended daily.",
  "Do not be impressed by those who started ahead of you. Be impressed by where you finish.",
  "Being broke is temporary. Thinking broke is a disease.",
  "You are not tired of the work. You are tired of not seeing results yet.",
  "The person you envy has scars you have not seen.",
  "Comparison is theft. Stay in your own lane.",
  "Every master was once a disaster.",
  "The gap between who you are and who you want to be is closed by action, not thought.",
  "Your body hears everything your mind says.",
  "Either run the day or the day runs you.",
  "Hardship is not a punishment. It is a qualification.",
  "Build the life you want or accept the one you get.",
  "Showing up is already more than most people do.",
  "Your worst day training is still better than your best day doing nothing.",
  "Stop romanticising where you are going. Start showing up for where you are.",
  "The loudest voice in the room is never the most disciplined one.",
  "You do not have to like it. You just have to do it.",
  "Failure is tuition. Pay it and move on.",
  "The quality of your questions determines the quality of your life.",
  "You cannot change what you refuse to confront.",
  "A small daily task done consistently beats a massive effort done rarely.",
  "Be proud of who you were yesterday. Be more today.",
  "Growth is uncomfortable. So is staying the same. Choose your discomfort.",
  "Every hard thing you have ever done has made you more capable of the next one.",
  "Your discipline today is your freedom tomorrow.",
  "Sweat today so you do not sweat tomorrow.",
  "The greatest wall you will ever climb is the one you build in your head.",
  "Weakness is a choice you make for long enough that it starts to feel like a trait.",
  "The men who make history are the ones who do not wait for it.",
  "You are one decision away from a completely different life.",
  "Stop asking for permission to be great.",
  "You cannot skip the process. The process is the point.",
  "The fire that burns you is the same fire that forges you.",
  "Do not pray for an easy life. Pray for the strength for a hard one.",
  "The problem is rarely the circumstances. It is almost always the mindset.",
  "Success is not luck. It is luck meeting preparation at the right moment.",
  "The harder the climb, the better the view.",
  "You are not doing this for anyone else. That is what makes it powerful.",
  "Excellence is not an act. It is a habit repeated until it becomes character.",
  "Your competition is sleeping. That is your opportunity.",
  "Earned confidence cannot be taken from you.",
  "Inaction is also a choice. And it has consequences.",
  "You were not made for an ordinary life. Stop living like you were.",
  "Nothing worth having arrives without a price. Pay it with a smile.",
  "The only way out is through.",
  "Be relentless not because it is easy but because it is who you are.",
  "You do not find yourself. You build yourself.",
  "The man who controls his appetite controls his life.",
  "Momentum is built one completed task at a time.",
  "Stop waiting for someone to give you permission to change your life.",
  "Today's discomfort is tomorrow's baseline.",
  "You are not running out of time. You are running out of excuses.",
  "Courage is not the absence of fear. It is doing the work despite it.",
  "Forget motivation. Build a system.",
  "The harder you work the luckier you seem.",
  "If it does not challenge you it does not change you.",
  "Own your morning. Own your day. Own your life.",
  "The best time to start was yesterday. The second best time is now.",
  "You are not a product of your circumstances. You are a product of your choices.",
  "Make the decision once. Execute it daily.",
  "The man who complains the most achieves the least.",
  "Your legacy is built in the moments no one celebrates.",
  "Clarity comes from action, not thought.",
  "The person who has given everything has nothing to regret.",
  "If you want to be uncommon you have to do uncommon things.",
  "No one is going to carry you to the finish line.",
  "The battle you fight every morning is the most important one.",
  "You earn the right to rest. You do not inherit it.",
  "Build something you are proud of or spend your life explaining why you didn't.",
  "Success is a series of small efforts repeated day in and day out.",
  "The man who does not read has no advantage over the man who cannot.",
  "Every version of you that quit had a reason. Every version that succeeded had a reason too.",
  "You are writing your story with every choice you make today.",
  "A good plan executed today beats a perfect plan tomorrow.",
  "The only approval you need is your own.",
  "Discipline is doing what needs to be done even when you do not want to do it.",
  "You have survived every hard day so far. Your record is perfect.",
  "Push yourself because no one else is going to do it for you.",
  "Make yourself proud.",
  "Outwork everyone. Outlearn everyone. Outlast everyone.",
  "The door to a better life is always open. You just have to walk through it.",
  "You will thank yourself later for what you do today.",
  "Small progress is still progress.",
  "The man you are today is the sum of every choice you have made.",
  "Great men are not born great. They are forged by the fire they chose to walk through.",
  "The strongest version of you exists. Go find him.",
  "Do not stop when you are tired. Stop when you are done.",
  "The cost of regret always exceeds the cost of discipline.",
  "Show up every day. The results will show up eventually.",
  "Your standards are the floor, not the ceiling.",
  "The world rewards those who finish.",
  "Whatever you do today, do it with everything you have.",
  "The man who does the work in the dark deserves the spotlight in the light.",
  "Chase progress not perfection.",
  "You do not have to be perfect. You have to be persistent.",
  "Every setback is a setup for a comeback if you choose to see it that way.",
  "Character is built in the moments no one is watching.",
  "Hard work is not punishment. It is the price of admission.",
  "You only fail when you stop trying.",
  "The version of you that made it is the one that did not quit on this exact day.",
  "Stop talking about who you want to be. Start being him.",
  "The work does not lie. It always tells the truth.",
  "You get what you tolerate. Raise the bar.",
  "Motivation gets you started. Discipline keeps you going.",
  "The man with a mission cannot be stopped by a bad mood.",
  "Build the life that makes others ask what changed.",
  "Every person you admire was once exactly where you are.",
  "The clock is ticking. Make it count.",
  "Success is not something that happens to you. It is something you create.",
  "You cannot heal what you refuse to acknowledge.",
  "The truth about progress is that it is invisible until it is undeniable.",
  "Hard choices, easy life. Easy choices, hard life.",
  "You were given this life because you are strong enough to live it.",
  "Obsession is just passion that decided not to take days off.",
  "The man who changes his habits changes his destiny.",
  "Your ceiling is someone else's floor. Keep climbing.",
  "Success is the sum of small efforts repeated day after day.",
  "You cannot pour motivation into someone who has not decided to change.",
  "The pain of discipline is temporary. The pride of achievement is permanent.",
  "You are closer than you think. Keep going.",
  "Decide who you want to be then do what that person does.",
  "The real competition is the man in the mirror.",
  "Make moves in silence. Let the results make noise.",
  "Every action is a brick. Build wisely.",
  "You were not made to fit in. You were made to stand out.",
  "The man who does not invest in himself will always work for someone who does.",
  "Stop starting over. Start continuing.",
  "There is honour in the attempt even when the outcome is failure.",
  "Be someone your younger self would have looked up to.",
  "You cannot buy back time. Spend it like it matters.",
  "The world will not care about your potential. Only your output.",
  "Outwork your doubts.",
  "The most dangerous person in the room is the one with nothing left to lose and everything to gain.",
  "Your habits are your destiny written in advance.",
  "Today is the day. Not tomorrow. Not Monday. Today.",
  "Feed your focus. Starve your distractions.",
  "The man who reads widely thinks deeply.",
  "You are not stuck. You are just unwilling to move yet.",
  "Resilience is not bouncing back. It is growing through.",
  "Do not downgrade your dream to match your current reality. Upgrade your effort.",
  "The greatest revenge is a life well built.",
  "You have to want it more than you are afraid of it.",
  "Be harder to stop than you are to start.",
  "You cannot borrow someone else's discipline. You have to build your own.",
  "Every elite was once a beginner. Every beginner is a potential elite.",
  "The moment you accept mediocrity is the moment you choose it.",
  "Pursue excellence privately. Let it be discovered publicly.",
  "A man who stands for nothing will fall for anything.",
  "The best project you will ever work on is yourself.",
  "You are not defined by where you start. You are defined by whether you finish.",
  "The things that are hardest to do are usually the ones most worth doing.",
  "Your energy is currency. Spend it on what matters.",
  "Every day is a chance to be better than yesterday.",
  "The graveyard is full of potential. Do not add yours to it.",
  "Rest when you need to. Not every time you want to.",
  "Silence your inner critic with results.",
  "You are not competing with anyone. You are completing yourself.",
  "Build yourself so well that no one can ignore you.",
  "The man who lacks discipline is a slave to his impulses.",
  "Your biggest obstacle is your best teacher.",
  "One day or day one. You choose.",
  "The man who masters himself masters everything.",
  "Do something today that your future self will be grateful for.",
  "Champions are not made in gyms. They are made from what they have inside.",
  "Make the hard choice. It was always the right one.",
  "Sacrifice now. Celebrate later.",
  "You are the only person responsible for the life you are living.",
  "The road to greatness is always under construction.",
  "Do not wish it were easier. Wish you were better.",
  "You are not average. Stop acting like it.",
  "The man who does not control his time does not control his life.",
  "Be relentless in the pursuit of what sets your soul on fire.",
  "The ones who win are the ones who show up after the ones who quit have left.",
  "A lion does not concern himself with the opinions of sheep.",
  "Your life is the message. Make sure it says something worth reading.",
  "Every hour you invest in yourself pays dividends for the rest of your life.",
  "You are the author. Stop letting circumstances write your story.",
  "The depth of your roots determines the height of your reach.",
  "Be so good they cannot ignore you.",
  "You have not come this far to only come this far.",
  "Turn the pain into fuel.",
  "The standard you walk past is the standard you accept.",
  "Wake up with determination. Go to bed with satisfaction.",
  "You do not have to be extreme. You just have to be consistent.",
  "The man who runs toward his fears shrinks them.",
  "Success is found in your daily routine, not in rare moments of inspiration.",
  "You are either building your empire or someone else's. Choose wisely.",
  "Do the work. Earn the life.",
  "The difference between where you are and where you want to be is what you do today.",
  "You will never regret the workout you did. Only the ones you skipped.",
  "No excuses. No shortcuts. No regrets.",
  "The measure of a man is not what he does in moments of comfort but in moments of challenge.",
  "Pressure is a privilege. It means you are in the game.",
  "The strongest people are not those who show strength but those who fight the battles no one sees.",
  "You are what you repeatedly do. Make it count.",
  "Stop wishing. Start working.",
  "The man who commits fully can never truly fail.",
  "Every day is a blank page. Write something worth reading.",
  "You are building something that matters. Do not stop now.",
  "The ones who change the world are the ones who refused to accept it as it was.",
  "Your dedication today is your freedom tomorrow.",
  "Be the hardest worker in the room. Every room.",
  "The best view comes after the hardest climb.",
  "You have everything you need to start. Start.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "Earn it every single day.",
  "You are not meant to figure it all out before you start. Start and figure it out.",
  "The man who trains alone trains the hardest.",
  "Your future is not determined by your past. It is determined by what you do next.",
  "Every sacrifice has a return. You just have to be patient enough to collect it.",
  "The man who gives everything leaves nothing to wonder about.",
  "Do not mistake stillness for peace. Sometimes it is just fear in disguise.",
  "You do not need more time. You need more intention.",
  "The greatest glory is not in never falling but in rising every time you fall.",
  "You are not too late. Someone started later than you and finished first.",
  "Build your body like it has to carry your ambitions. Because it does.",
  "Doubt kills more dreams than failure ever will.",
  "The man who outlasts is always the man who wins.",
  "You get one body. Treat it accordingly.",
  "There is no version of success that does not require sacrifice.",
  "The only easy day was yesterday.",
  "If you are not uncomfortable you are not growing.",
  "You do not need to see the whole staircase. Just take the next step.",
  "The match is won in the preparation, not the performance.",
  "Every failure is a data point. Collect it and adjust.",
  "A man who does not stand up for himself teaches others to do the same.",
  "You are never really ready. You just get tired of waiting.",
  "The man who chases two rabbits catches neither. Pick one. Go all in.",
  "Your character is what you do on the days no one is watching and nothing is on the line.",
  "Stop being afraid of what could go wrong. Focus on what could go right.",
  "The man who earns his rest sleeps better than the man who takes it.",
  "You do not need luck. You need leverage. Build it.",
  "Every struggle you face is shaping the person you are becoming.",
  "The man who reads today leads tomorrow.",
  "You will not always feel like it. Do it anyway.",
  "The strongest walls are built from broken stones.",
  "Your potential is not found in your comfort zone.",
  "Make your work speak so loudly that your words become unnecessary.",
  "The man who masters his mornings masters his life.",
  "You are not waiting for the right moment. You are avoiding the hard one.",
  "Build habits so strong that your bad days look like someone else's best.",
  "The road is long. The work is hard. The outcome is worth it.",
  "You were not put here to be ordinary.",
  "Act like the person you want to become until you cannot tell the difference.",
  "The man who refuses to quit is impossible to defeat.",
  "Brick by brick. Day by day. That is how empires are built.",
  "Your level of success will rarely exceed your level of personal development.",
  "Go further than you thought you could. That is where you find out who you are.",
  "The man who masters his mind masters his world.",
  "The last step is always the hardest. Take it anyway.",
];

export function getDailyQuote(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return dailyQuotes[dayOfYear % dailyQuotes.length];
};

export const subArchetypeTiers: Record<string, { core: string[]; strong: string[]; relevant: string[] }> = {
  'Weight Loss': {
    core: ['Sleep (7-9 hours)', 'Eating healthy (no sugar, no processed, RDIs)', 'Any form of cardio', 'Hit daily protein and calories', 'Debloat protocol'],
    strong: ['Digestive walk', 'At least 3L of water', 'Training (weights/calisthenics/plyometrics)', 'Stretching'],
    relevant: ['Sauna', 'Cold shower', 'Taking supplements', 'At least 30 min sunlight (with SPF)'],
  },
  'Longevity': {
    core: ['Sleep (7-9 hours)', 'At least 30 min sunlight (with SPF)', 'Eating healthy (no sugar, no processed, RDIs)', 'Taking supplements', 'At least 3L of water'],
    strong: ['Stretching', 'Meditating/NSDR/breathing exercises', 'Cold shower', 'Sauna', 'Going for a walk', 'Any form of cardio'],
    relevant: ['Journal', 'Sit in silence 10 min', 'Debloat protocol'],
  },
  'Energy Optimisation': {
    core: ['Sleep (7-9 hours)', 'Delay coffee 90 min after waking', 'No phone for 60 min after waking', 'At least 30 min sunlight (with SPF)', 'At least 3L of water'],
    strong: ['Nutrient dense breakfast', 'Taking supplements', 'Meditating/NSDR/breathing exercises', 'Any form of cardio'],
    relevant: ['Stretching', 'Cold shower', 'Journal', 'Sit in silence 10 min', 'Eating healthy (no sugar, no processed, RDIs)'],
  },
  'Bulk': {
    core: ['Sleep (7-9 hours)', 'Training (weights/calisthenics/plyometrics)', 'Hit daily protein and calories', 'Nutrient dense breakfast', 'Gym rest day'],
    strong: ['Taking supplements', 'Eating healthy (no sugar, no processed, RDIs)', 'Sauna'],
    relevant: ['Stretching', 'Cold shower', 'At least 3L of water'],
  },
  'Cut': {
    core: ['Sleep (7-9 hours)', 'Any form of cardio', 'Eating healthy (no sugar, no processed, RDIs)', 'Hit daily protein and calories', 'Debloat protocol'],
    strong: ['Training (weights/calisthenics/plyometrics)', 'Digestive walk', 'At least 3L of water'],
    relevant: ['Sauna', 'Cold shower', 'Stretching', 'Taking supplements'],
  },
  'Maintain / Recomp': {
    core: ['Sleep (7-9 hours)', 'Training (weights/calisthenics/plyometrics)', 'Hit daily protein and calories', 'Eating healthy (no sugar, no processed, RDIs)'],
    strong: ['Any form of cardio', 'Gym rest day', 'Taking supplements'],
    relevant: ['Stretching', 'Sauna', 'Cold shower', 'At least 3L of water'],
  },
  'Sport-Specific': {
    core: ['Sleep (7-9 hours)', 'Training (weights/calisthenics/plyometrics)', 'Any form of cardio', 'Gym rest day', 'Stretching'],
    strong: ['Hit daily protein and calories', 'Taking supplements', 'Cold shower'],
    relevant: ['Sauna', 'At least 3L of water', 'Eating healthy (no sugar, no processed, RDIs)'],
  },
  'Early Stage Builder': {
    core: ['Sleep (7-9 hours)', 'Working in deep focus (1hr minimum)', 'Learn something directly applicable to business', 'Brainstorm session (15 min minimum)', 'Outreach to a potential client or collaborator'],
    strong: ['Work on the business not in it (30min strategic)', 'Review finances/business metrics', 'Reading (15 min or 10 pages minimum)', 'No unnecessary social media'],
    relevant: ['Listening to a podcast (30 min minimum)', 'Journal', 'Networking', 'Any form of cardio', 'Training (weights/calisthenics/plyometrics)'],
  },
  'Operator / Scaler': {
    core: ['Sleep (7-9 hours)', 'Working in deep focus (1hr minimum)', 'Work on the business not in it (30min strategic)', 'Review finances/business metrics', 'Networking'],
    strong: ['Outreach to a potential client or collaborator', 'Sales or negotiation practice', 'Financial planning session', 'No unnecessary social media'],
    relevant: ['Reading (15 min or 10 pages minimum)', 'Listening to a podcast (30 min minimum)', 'Journal', 'Brainstorm session (15 min minimum)'],
  },
  'Freelancer': {
    core: ['Sleep (7-9 hours)', 'Working in deep focus (1hr minimum)', 'Outreach to a potential client or collaborator', 'Sales or negotiation practice', 'Seek feedback on your work'],
    strong: ['Review finances/business metrics', 'Learn something directly applicable to business', 'Networking', 'No unnecessary social media'],
    relevant: ['Brainstorm session (15 min minimum)', 'Listening to a podcast (30 min minimum)', 'Journal', 'Reading (15 min or 10 pages minimum)'],
  },
  'Academic': {
    core: ['Sleep (7-9 hours)', 'Study session', 'Active recall / flashcard session', 'Write a summary of what you studied', 'Working in deep focus (1hr minimum)'],
    strong: ['Teach someone what you learned today', 'Solve a problem from scratch', 'No unnecessary social media', 'Sit in silence 10 min'],
    relevant: ['Reading (15 min or 10 pages minimum)', 'Listening to a podcast (30 min minimum)', 'Journal', 'Language practice session'],
  },
  'Self-Taught': {
    core: ['Sleep (7-9 hours)', 'Learn a new skill (15 min minimum)', 'Working in deep focus (1hr minimum)', 'Active recall / flashcard session', 'Language practice session'],
    strong: ['Study session', 'Solve a problem from scratch', 'Seek feedback on your work', 'Reading (15 min or 10 pages minimum)'],
    relevant: ['Listening to a podcast (30 min minimum)', 'Journal', 'Brainstorm session (15 min minimum)', 'Sit in silence 10 min'],
  },
  'Reader': {
    core: ['Sleep (7-9 hours)', 'Reading (15 min or 10 pages minimum)', 'Listening to a podcast (30 min minimum)', "Study someone you admire's work", 'Write a summary of what you studied'],
    strong: ['Journal', 'Teach someone what you learned today', 'Sit in silence 10 min'],
    relevant: ['Active recall / flashcard session', 'Working in deep focus (1hr minimum)', 'Language practice session'],
  },
  'Short Form': {
    core: ['Sleep (7-9 hours)', 'Publish something (post, video, article)', 'Batch content creation session (1hr minimum)', 'Engage with your audience', 'Working in deep focus (1hr minimum)'],
    strong: ['Brainstorm session (15 min minimum)', "Study someone you admire's work", 'Seek feedback on your work', 'Doing something creative'],
    relevant: ['Journal', 'Reading (15 min or 10 pages minimum)', 'Listening to a podcast (30 min minimum)', 'Learn a new skill (15 min minimum)'],
  },
  'Long Form': {
    core: ['Sleep (7-9 hours)', 'Publish something (post, video, article)', 'Batch content creation session (1hr minimum)', 'Working in deep focus (1hr minimum)', 'Learn a new skill (15 min minimum)'],
    strong: ['Brainstorm session (15 min minimum)', "Study someone you admire's work", 'Seek feedback on your work', 'Doing something creative'],
    relevant: ['Journal', 'Reading (15 min or 10 pages minimum)', 'Engage with your audience', 'Listening to a podcast (30 min minimum)'],
  },
  'Writer': {
    core: ['Sleep (7-9 hours)', 'Publish something (post, video, article)', 'Working in deep focus (1hr minimum)', 'Journal', 'Reading (15 min or 10 pages minimum)'],
    strong: ['Brainstorm session (15 min minimum)', 'Write a summary of what you studied', 'Seek feedback on your work', "Study someone you admire's work"],
    relevant: ['Doing something creative', 'Listening to a podcast (30 min minimum)', 'Learn a new skill (15 min minimum)', 'Sit in silence 10 min'],
  },
  'Stoic': {
    core: ['Sleep (7-9 hours)', 'Doing something you hate daily', 'Cold shower', 'Sit in silence 10 min', 'No lustful behaviours', 'Being grounded (end of day reflection)'],
    strong: ['No unnecessary social media', 'Not on phone too much', 'Journal', 'Standing for your morals (end of day reflection)'],
    relevant: ['Meditating/NSDR/breathing exercises', 'Stretching', 'Reading (15 min or 10 pages minimum)', 'Going for a walk'],
  },
  'Spiritual': {
    core: ['Sleep (7-9 hours)', 'Meditating/NSDR/breathing exercises', 'Sit in silence 10 min', 'Journal', '1 hour silence', 'Being grounded (end of day reflection)'],
    strong: ['1 day fast', 'View sunset', 'Be content with yourself (end of day reflection)'],
    relevant: ['Cold shower', 'Going for a walk', 'Reading (15 min or 10 pages minimum)', 'Stretching'],
  },
  'Connector': {
    core: ['Sleep (7-9 hours)', 'Being social', 'Organise or attend a social event', "Call or meet a friend you haven't spoken to in a while", 'Do something kind without expecting anything'],
    strong: ['Initiate a conversation with a stranger', 'Give someone a genuine compliment', 'Active listening — full presence, no phone'],
    relevant: ['Networking', 'Practice public speaking (mirror/recording)', 'Journal'],
  },
  'Public Speaker': {
    core: ['Sleep (7-9 hours)', 'Practice public speaking (mirror/recording)', 'Initiate a conversation with a stranger', 'Doing something you hate daily'],
    strong: ['Being social', 'Active listening — full presence, no phone', 'Organise or attend a social event', 'Journal'],
    relevant: ['Give someone a genuine compliment', 'Reading (15 min or 10 pages minimum)', 'Working in deep focus (1hr minimum)'],
  },
  'Dating / Charisma': {
    core: ['Sleep (7-9 hours)', 'Initiate a conversation with a stranger', 'Give someone a genuine compliment', 'Being social', 'Good posture'],
    strong: ['Active listening — full presence, no phone', 'Do something kind without expecting anything', 'Think before speaking (end of day reflection)', 'Being grounded (end of day reflection)'],
    relevant: ['Practice public speaking (mirror/recording)', 'Journal', 'Cold shower', 'Training (weights/calisthenics/plyometrics)'],
  },
  'Father': {
    core: ['Sleep (7-9 hours)', 'Spend quality time with family (no phones)', 'Have a meaningful conversation with a family member', 'Plan a family activity', 'Do something kind without expecting anything'],
    strong: ['Tell someone you love them', 'Being social', 'Active listening — full presence, no phone', 'Standing for your morals (end of day reflection)'],
    relevant: ['Financial planning session', 'Journal', 'Going for a walk', 'Eating healthy (no sugar, no processed, RDIs)'],
  },
  'Partner': {
    core: ['Sleep (7-9 hours)', 'Spend quality time with family (no phones)', 'Have a meaningful conversation with a family member', 'Tell someone you love them', 'Do something kind without expecting anything'],
    strong: ['Active listening — full presence, no phone', 'Being grounded (end of day reflection)', 'Be content with yourself (end of day reflection)', 'Think before speaking (end of day reflection)'],
    relevant: ['Journal', 'Going for a walk', 'Plan a family activity', 'Standing for your morals (end of day reflection)'],
  },
  'Provider': {
    core: ['Sleep (7-9 hours)', 'Financial planning session', 'Working in deep focus (1hr minimum)', 'Review finances/business metrics', 'Standing for your morals (end of day reflection)'],
    strong: ['Work on the business not in it (30min strategic)', 'Outreach to a potential client or collaborator', 'Networking', 'Plan a family activity'],
    relevant: ['Reading (15 min or 10 pages minimum)', 'Listening to a podcast (30 min minimum)', 'Journal', 'Eating healthy (no sugar, no processed, RDIs)'],
  },
  'Skin / Grooming': {
    core: ['Sleep (7-9 hours)', 'Skincare routine', 'At least 30 min sunlight (with SPF)', 'At least 3L of water', 'Mouth taping', 'Mewing'],
    strong: ['Eating healthy (no sugar, no processed, RDIs)', 'Taking supplements', 'Debloat protocol', 'Cold shower'],
    relevant: ['Stretching', 'Sauna', 'Good posture', 'Nutrient dense breakfast'],
  },
  'Style': {
    core: ['Sleep (7-9 hours)', 'Good posture', 'Skincare routine', 'Mewing', 'At least 30 min sunlight (with SPF)'],
    strong: ['Going for a walk', 'Being social', 'Seek feedback on your work', "Study someone you admire's work"],
    relevant: ['Cold shower', 'Eating healthy (no sugar, no processed, RDIs)', 'At least 3L of water', 'Training (weights/calisthenics/plyometrics)'],
  },
  'Aesthetic Physique': {
    core: ['Sleep (7-9 hours)', 'Training (weights/calisthenics/plyometrics)', 'Any form of cardio', 'Hit daily protein and calories', 'Eating healthy (no sugar, no processed, RDIs)'],
    strong: ['Gym rest day', 'Debloat protocol', 'Taking supplements', 'Cold shower'],
    relevant: ['Stretching', 'Sauna', 'At least 3L of water', 'Good posture'],
  },
};

export const activityCategory: Record<string, string> = Object.fromEntries(
  categories.flatMap(cat => cat.activities.map(a => [a.name, cat.title]))
);

export const activityFreq: Record<string, Activity['freq']> = Object.fromEntries(
  categories.flatMap(cat => cat.activities.map(a => [a.name, a.freq]))
);

export const activityXp: Record<string, number> = Object.fromEntries(
  categories.flatMap(cat => cat.activities.map(a => [a.name, a.xp]))
);

export function getMultiplier(
  activityName: string,
  archetype: string | null,
  subArchetype: string | null,
  loggedToday: string[],
  sideArchetypes: string[] = [],
): number {
  if (!archetype) return 1.0;

  if (archetype === 'Jack of All Trades') {
    const catOfThis = activityCategory[activityName];
    const cats = new Set([
      ...loggedToday.map(a => activityCategory[a]).filter(Boolean),
      ...(catOfThis ? [catOfThis] : []),
    ]);
    const n = cats.size;
    if (n >= 10) return 1.30;
    if (n >= 9) return 1.25;
    if (n >= 8) return 1.20;
    if (n >= 7) return 1.15;
    if (n >= 6) return 1.10;
    if (n >= 5) return 1.05;
    return 1.0;
  }

  if (subArchetype) {
    const tiers = subArchetypeTiers[subArchetype];
    if (tiers) {
      if (tiers.core.includes(activityName)) return 1.20;
      if (tiers.strong.includes(activityName)) return 1.10;
      if (tiers.relevant.includes(activityName)) return 1.05;
    }
  }

  if (activityArchetypes[activityName]?.includes(archetype)) return 1.0;
  if (sideArchetypes.some(sa => activityArchetypes[activityName]?.includes(sa))) return 0.9;
  return 0.7;
}

export const archetypes = [
  { name: 'Healthy Guy', description: 'Weight Loss · Longevity · Energy Optimisation' },
  { name: 'Gymbro / Athlete', description: 'Bulk · Cut · Maintain / Recomp · Sport-Specific' },
  { name: 'Entrepreneur', description: 'Early Stage Builder · Operator / Scaler · Freelancer' },
  { name: 'Scholar', description: 'Academic · Self-Taught · Reader' },
  { name: 'Creator', description: 'Short Form · Long Form · Writer' },
  { name: 'Monk', description: 'Stoic · Spiritual' },
  { name: 'Social Guy', description: 'Connector · Public Speaker · Dating / Charisma' },
  { name: 'Family Man', description: 'Father · Partner · Provider' },
  { name: 'Looksmaxer', description: 'Skin / Grooming · Style · Aesthetic Physique' },
  { name: 'Jack of All Trades', description: 'No sub-archetypes' },
];

export function localDateString(d: Date = new Date()): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export const subArchetypes: Record<string, string[]> = {
  'Healthy Guy': ['Weight Loss', 'Longevity', 'Energy Optimisation'],
  'Gymbro / Athlete': ['Bulk', 'Cut', 'Maintain / Recomp', 'Sport-Specific'],
  'Entrepreneur': ['Early Stage Builder', 'Operator / Scaler', 'Freelancer'],
  'Scholar': ['Academic', 'Self-Taught', 'Reader'],
  'Creator': ['Short Form', 'Long Form', 'Writer'],
  'Monk': ['Stoic', 'Spiritual'],
  'Social Guy': ['Connector', 'Public Speaker', 'Dating / Charisma'],
  'Family Man': ['Father', 'Partner', 'Provider'],
  'Looksmaxer': ['Skin / Grooming', 'Style', 'Aesthetic Physique'],
  'Jack of All Trades': [],
};
